### ISSUE TITLE
Issue with is_prime()

### ISSUE THREAD

**Issue by Shiiyu** [nstringham/cosc-341-rust#2]
All primes after 2 and 3 are under 6x +1 and 6x - 1, but not all of those values are primes, resulting in multiple false positives. It would require a rewrite, but you also need to check if the value is divisible by each of the previous primes as well to get the correct result for display_primes().

**Comment by nstringham** [comment]
Thanks. I don't think I fully understand, can you give an example of one of these false positives?

**Comment by Shiiyu** [comment]
As an example, if you were to run display_primes(50), you would get the following: 
2, 3, 5, 7, 11, 13, 17, 19, 23, 25, 29, 31, 35, 37, 41, 43, 47, 49

In this set, 25 is a false positive as it is divisible by 5, 35 is also divisible by 5, and 49 is divisible by 7. Checking if the candidate for being a prime is equal to previous primes will eliminate these false positives as you can see, all three of those false positives are divisible by previous primes.

**Comment by nstringham** [comment]
ok I figured out what was going on I was checking those primes but I was returning true instead of false for some reason here is the new output of display_primes(50) `2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47`
